ProjetoFinal/Models/Produto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinal.Models
{
    public class Produto
    {
        public int Id { get; set; }

        /// <summary>
        /// Código EAN (internacional) do produto.
        /// </summary>
        [StringLength(30), DisplayName("Código de Barras")]
        public string? Ean { get; set; }

        [StringLength(250)]
        public string Nome { get; set; } = null!;

        [DisplayName("Descrição")]
        public string? Descricao { get; set; }

        [DisplayName("Preço")]
        public float Preco { get; set; }

        [DisplayName("Estoque Atual")]
        public float EstoqueAtual { get; set; }
    }
}

ProjetoFinal/Controllers/EstoqueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoFinal.Data;
using ProjetoFinal.Repositorio;

namespace ProjetoFinal.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ProdutoRepositorio produtoRepositorio;

        public EstoqueController(ApplicationDbContext context, ProdutoRepositorio produtoRepositorio)
        {
            _context = context;
            this.produtoRepositorio = produtoRepositorio;
        }

        // GET: Estoque
        public async Task<IActionResult> Index(int id)
        {
            var produto = produtoRepositorio.Buscar(id);
            ViewBag.Produto = produto;
            var applicationDbContext = _context.Estoque.Where(a=>a.ProdutoId == id).Include(e => e.Venda);
            return View(await applicationDbContext.ToListAsync());
        }

    }
}

ProjetoFinal/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;
using ProjetoFinal.Repositorio;

namespace ProjetoFinal.Controllers
{
    [Authorize]
    public class ProdutosController : BaseController
    {
        private readonly ProdutoRepositorio _produtoRepositorio;

        public ProdutosController(ProdutoRepositorio produtoRepositorio)
        {
            this._produtoRepositorio = produtoRepositorio;
        }

        // GET: Produtos
        public IActionResult Index()
        {
              return View(_produtoRepositorio.Listar().ToList());
        }

        // GET: Produtos/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                SetErroMessagem("Produto não econtrado");
                return RedirectToAction(nameof(Index));
            }

            var produto = _produtoRepositorio.Buscar(id.Value);
            if (produto == null)
            {
                SetErroMessagem("Produto não econtrado");
                return RedirectToAction(nameof(Index));
            }

            return View(produto);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ean,Nome,Descricao,Preco,EstoqueAtual")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                _produtoRepositorio.Adicionar(produto);
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                SetErroMessagem("Produto não econtrado");
                return RedirectToAction(nameof(Index));
            }

            var produto = _produtoRepositorio.Buscar(id.Value);
            if (produto == null)
            {
                SetErroMessagem("Produto não econtrado");
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ean,Nome,Descricao,Preco,EstoqueAtual")] Produto produto)
        {
            if (id != produto.Id)
            {
                RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                var result = _produtoRepositorio.Atualizar(id, produto);
                if (result.IsFailed)
                {
                    SetErroMessagem(result.Errors.First().Message);
                    return RedirectToAction(nameof(Edit), new { id });
                }
                return RedirectToAction(nameof(Index));
            }

            return View(produto);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                SetErroMessagem("Produto não encontrado.");
                return RedirectToAction(nameof(Index));
            }

            var produto = _produtoRepositorio.Buscar(id.Value);
            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _produtoRepositorio.Deletar(id);

            if (result.IsFailed)
                SetErroMessagem(result.Errors.First().Message);
            else
                SetSucessoMessagem("Produto removido com sucesso.");

            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoFinal/Views/Produtos/Create.cshtml
@model ProjetoFinal.Models.Produto

@{
    ViewData["Title"] = "Cadastrar novo produto";
}

<h4>Cadastrar novo produto</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstoqueAtual" class="control-label"></label>
                <input asp-for="EstoqueAtual" class="form-control" />
                <span asp-validation-for="EstoqueAtual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para listagem de produtos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoFinal/Views/Produtos/Delete.cshtml
@model ProjetoFinal.Models.Produto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstoqueAtual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstoqueAtual)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjetoFinal/Views/Produtos/Details.cshtml
@model ProjetoFinal.Models.Produto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstoqueAtual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstoqueAtual)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Delete" asp-route-id="@Model?.Id">Deletar</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjetoFinal/Views/Produtos/Edit.cshtml
@model ProjetoFinal.Models.Produto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ean" class="control-label"></label>
                <input asp-for="Ean" class="form-control" />
                <span asp-validation-for="Ean" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstoqueAtual" class="control-label"></label>
                <input asp-for="EstoqueAtual" class="form-control" />
                <span asp-validation-for="EstoqueAtual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoFinal/Views/Produtos/Index.cshtml
@model IEnumerable<ProjetoFinal.Models.Produto>

@{
    ViewData["Title"] = "Lista de Produtos";
}

<h1>Listagem de Produtos da loja</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Cadastrar Produto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ean)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstoqueAtual)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstoqueAtual)
            </td>
            <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-controller="Estoque" asp-action="Index" asp-route-id="@item.Id">Estoque</a>
            </td>
        </tr>
}
    </tbody>
</table>